#!/usr/bin/env php
<?php
/*
 * This file is part of kmsdotenv.
 *
 *  (c) Signature Tech Studio, Inc <info@stechstudio.com>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

if (version_compare('7.2.0', PHP_VERSION, '>')) {
    fwrite(
        STDERR,
        sprintf(
            'This version of KMSDotEnv is supported on PHP 7.2.' . PHP_EOL .
            'You are using PHP %s (%s).' . PHP_EOL,
            PHP_VERSION,
            PHP_BINARY
        )
    );
    die(1);
}
if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}
foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('KMSDOTENV_COMPOSER_INSTALL', $file);
        break;
    }
}
unset($file);
if (!defined('KMSDOTENV_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );
    die(1);
}
require KMSDOTENV_COMPOSER_INSTALL;

use STS\EnvSecurity\TextUI\Edit;
use STS\EnvSecurity\TextUI\Encrypt;
use STS\EnvSecurity\TextUI\Decrypt;
use Symfony\Component\Console\Application;

$application = new Application('kms', '1.0.0');
$application->add(new Edit());
$application->add(new Encrypt());
$application->add(new Decrypt());

$application->run();