name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php: "8.2"
            phpunit: "11"
          - php: "8.5"
            phpunit: "12"

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v4

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v4
        env:
          APP_ENV: testing
          APP_KEY: zbcmF4pUB5v4ShHiq6kJbWTQyiT8CUyw
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          php_version: ${{ matrix.php }}
          version: ${{ matrix.phpunit }}
